version: '3'

services:
  proxy:
    image: docker-nginx:0.1
    container_name: proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf.d
    environment:
      TZ: Asia/Seoul
    depends_on:
      - app3
      - app4

#  mysql:
#    container_name: mysql:latest
#    environment:
#      MYSQL_DATABASE: test_db
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ROOT_HOST: '%'
#    ports:
#      - 3306:3306

  app3:
    container_name: app3
    image: app:0.1
    ports:
      - 8081:8081


  app4:
    container_name: app4
    image: app:0.2
    ports:
      - 8082:8082
#    depends_on:
#      - mysql

