spring:

  profiles:
    group:
      "blue" : "blue"
      "green" : "green"
    default: "blue"

  datasource:
    url: jdbc:mysql://test_db
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MYSQL5Dialect
#    generate-ddl: true
#    show-sql: true


---
spring:
  config:
    activate:
      on-profile: "blue"

---
spring:
  config:
    activate:
      on-profile: "green"